# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Define the VM Name
  config.vm.define "app" do |app|

    # Specify the box to use
    app.vm.box = "bento/ubuntu-20.04"

    # Set the VM's hostname
    app.vm.hostname = "app-vm"

    # Forward the guest port 3000 to the host port 8080
    app.vm.network "forwarded_port", guest: 3000, host: 8080

    # Forward the guest port 27017 to the host port 27017 for MongoDB
    app.vm.network "forwarded_port", guest: 27017, host: 27017

    # Configure the VM's resources
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end

    # First shell provisioner for installing MongoDB and Node.js
    app.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y git curl wget gnupg ca-certificates

      echo "----------> Installing MongoDB-org"
      curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
      sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor

      echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list

      sudo apt-get update
      sudo apt-get install -y mongodb-org
      sudo systemctl start mongod

      echo "----------> Installing Node.js"
      sudo mkdir -p /etc/apt/keyrings
      curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

      NODE_MAJOR=20
      echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

      sudo apt-get update
      sudo apt-get install -y nodejs
      sudo npm install -g nodemon
    SHELL

    # Second shell provisioner for setting up the QuoteFinder project
    app.vm.provision "shell", privileged: false, inline: <<-SHELL
      echo "----------> Downloading QuoteFinder"
      cd /home/vagrant
      if [ -d "./QuoteFinder" ]; then
        echo "repo already cloned..."
      else
        #git clone https://github.com/mickesv/QuoteFinder/
        git clone https://github.com/geco97/QFStandalone/
      fi
      cp -r QuoteFinder/Containers/Version1 .

      echo "----------> Setting up QFStandalone"
      cd Version1/QFStandalone
      npm install
    SHELL

  end
end
